config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :galleries
  
  devise_for :users

  root 'pages#home'

  get 'dashboard', to: 'pages#dashboard'
  get 'clinicas', to: 'pages#clinicas'

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:uuid', to: 'transactions#pickup', as: :pickup
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :sales
  has_attached_file :image
  has_attached_file :resource

  validates_attachment :image, presence: true,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
  message: "Only images allowed!"

  validates_attachment :resource, presence: true,
  content_type: { content_type: "application/pdf" },
  message: "Only PDF allowed!"

  validates_numericality_of :price,
  greater_than: 49, message: "Price must be at least 50 cents"
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag book.image.url, class: "img-responsive" %>
        <div class="caption">
          <h4><%= link_to book.name, book_path(book) %></h4>
          <p>US$ <%= book.price/100 %></p>
          <% if book.availability? %>
            <p>Book Available</p>
          <% else %>
            <p>Book <em>Not</em> Available</p>
          <% end %>
        </div>
      </div>
    </div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, label: false, require: true,
                placeholder: "Name of the book" %>
    <%= f.input :author, label: false,  require: true,
                placeholder: "Name of the author" %>
    <%= f.input :description, label: false,  require: true,
                placeholder: "Little description of the book" %>
    <%= f.input :image %>
    <%= f.input :resource %>
    <%= f.input :price, label: false,  require: true,
                placeholder: "Price of the book" %>
    <%= f.input :availability %>



    <%= f.button :submit, class: "btn btn-success btn-block" %>

<% end %>

app/views/books/edit.html.erb
<h1 class="page-header">Editing Book
  <%= link_to 'Delete Book', book_path(@book), method: :delete, class: "btn btn-danger pull-right" %>
  <%= link_to 'Show Book', book_path(@book), class: "btn btn-info pull-right" %>
  <%= link_to 'All Books', books_path, class: "btn btn-info pull-right" %>
</h1>



<%= render 'form', book: @book %>

app/views/books/index.html.erb
<h1 class="page-header">Books
  <%= link_to 'New Book', new_book_path, class: "btn btn-info pull-right" %></h1>



<div class="row">

  <%= render @books %>

</div>

app/views/books/new.html.erb
<h1 class="page-header">New Book
      <%= link_to 'Back', books_path, class: "btn btn-default pull-right" %></h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-6 text-center">
    <%= image_tag @book.image.url, class: "img-responsive" %>
  </div>
  <div class="col-md-6 text-center">

    <h3 class="page-header"><strong><%= @book.name %></strong> by <strong><%= @book.author %></strong></h3>
    <p><%= @book.description %></p>
    <p><strong>US$: <%= @book.price/100 %></strong></p>

    <% if current_user %>
      <%= form_tag buy_path(slug: @book.slug) do %>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @book.name %>"
          data-amount="<%= @book.price %>"
          data-email="<%= current_user.email %>"
          data-locale="auto">
      </script>
      <% end %>
    <% else %>
      <p>Please log in to purchase this book</p>
    <% end %>

    <div class="btn-group btn-group-justified">
      <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary btn-block" %>
      <%= link_to 'Back', books_path, class: "btn btn-primary btn-block"%>
    </div>

  </div>
</div>