config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :galleries
  
  devise_for :users

  root 'pages#home'

  get 'dashboard', to: 'pages#dashboard'
  get 'clinicas', to: 'pages#clinicas'

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:uuid', to: 'transactions#pickup', as: :pickup
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>">
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= msg %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ebook', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Gallery', galleries_path %>
        </li>
        <li>
          <%= link_to 'Books', books_path %>
        </li>
        <% if current_user %>
          <li>
            <%= link_to 'Dashboard', dashboard_path %>
          </li>
          <li>
            <%= link_to 'Profile', edit_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Log In', new_user_session_path %>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>

      <% flash.each do |type, msg| %>
        <div class="alert alert-info alert-dismissible fade-in">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>